config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'search/input'
    post 'session/login'
    get 'session/logout'
    post 'session/logout'
    get 'session/login'
    post 'session/create'

    root 'main_room#main', as: 'main'
    get 'main_room/profile', as: 'profile'
    get 'main_room/join', as: 'join'
    get 'main_room/join_invite', as: 'join_invite'
    post 'main_room/roomjoininvite'
    post 'main_room/reject_invite', as: 'reject_invite'
    get 'main_room/showroom', as: 'showroom'
    get 'main_room/showhistory', as: 'history'
    post 'res', to: 'main_room#show'
    get 'main_room/rules', as: 'rules'

    post 'rooms/deleteuser', as: 'deleteuser'
    post 'rooms/lottery', as: 'lottery'
    get 'rooms/createroom', as: 'createroom'
    post 'rooms/destroy', as: 'destroyroom'
    post 'rooms/quit', as: 'quit'
    post 'rooms/roomjoin'

    get 'search/add', as: 'add'
    get 'search/input', as: 'search'
    post 'result', to: 'search#show'
    post 'search/addroom', as: 'addroom'

    post 'users/destroy', as: 'destroy'

    resources :users, :rooms
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :check, only: :show
  def input; end

  def show
    @inp = params[:n]
    @result = User.where('username LIKE ?', "%#{@inp}%").all
  end

  def add
    @mas = []
    RoomUser.where('user_id = ? AND role = ?', current_user.id, 'admin').all.each do |x|
      @mas.push(Room.find_by(id: x.room_id).room_name)
    end
  end

  def addroom
    id = params[:id]
    roomname = params[:room]
    unless RoomUser.where('user_id = ? AND room_id = ?', id, Room.find_by(room_name: roomname).id).empty?
      redirect_to add_url(id: id), notice: t('.user')
      return
    end
    if Invite.find_by(user_id: id, room_id: Room.find_by(room_name: roomname).id)
      redirect_to add_url(id: id), notice: t('.invite')
      return
    end
    @invite = Invite.create(user_id: id, room_id: Room.find_by(room_name: roomname).id, inviter_id: current_user.id)
    redirect_to main_path, notice: t('.success')
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_result.html.erb
<div id="result" class="table">
<h1 class="color-text center"> <%= t('.title') %> </h1>
<table class="table table-striped fs-1">
    <thead>
    <tr>
    <th scope="col">#</th>
    <th scope="col"> <%= t('.login') %> </th>
    </tr>
    <thead>

    <tbody>
    <% @result.each_with_index do |el, idx| %>
    <%unless el.id==current_user.id %>
    <tr>
        <td> <%= idx+1 %>.</td>
        <td class="col-5"> <%=link_to el.username, add_url(:id => el.id ), id:"link_to_user" %> </td>
    </tr>
    <%end%>
    <% end %>
    </tbody>
</table>
</div>

app/views/search/add.html.erb
<%unless flash[:notice].blank?%>
  <h2 style = 'color:red'><%=flash[:notice]%></h2>
<%end%>
<div class="col-5 mx-auto text-center fs-1 bgo justify-content-center mt-5">
<div class="text-light">
<%= t('.title')%>
<%= User.find_by(id: params[:id]).username%>
</div>
<div class="fs-2 p-4">
<% if RoomUser.where('user_id = ? AND role = ?', current_user, 'admin').take %>
<%= form_with url: addroom_url(:id => params[:id]), method: :post, class: "center" do |form| %>
    <%= form.select :room, @mas%>
    <br>
    <%= form.submit t('.send'), class:"btn btn-primary fs-2 mt-4", id:"btn_send_invite_room"%>
<%end%>
<% else %>
<div class="text-danger">
<%= t('.not') %>
</div>
<%end%>
</div >
<%=link_to t('.link'), search_url, class: "link-light" %> |
<%=link_to t('.main'), main_path, class: "link-light" %>
</div>

app/views/search/input.html.erb
<div class="col-5 mx-auto text-center fs-1 bgo mt-5 ">
<div class="text-light">
<%= t('.title') %>
</div>
<div class="fs-2 p-4 col-5 mx-auto">
<%= form_with url: result_path, class: "row gy-3 gx-3 ", id: "palindrom_form" do |form| %>
    <%= form.text_field :n, class: "form-control" %>
    <br>
    <%= form.submit t('.search'), class:"btn btn-dark fs-3", id:"btn_find_user" %>
</div >
<%end%>
<%=link_to t('.to_main'), main_path, class: "link-light" %>
</div>

<div id="result" class="table"></div>

app/views/search/show.turbo_stream.erb
<%= turbo_stream.replace 'result', partial: 'result' %>