config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'search/input'
    post 'session/login'
    get 'session/logout'
    post 'session/logout'
    get 'session/login'
    post 'session/create'

    root 'main_room#main', as: 'main'
    get 'main_room/profile', as: 'profile'
    get 'main_room/join', as: 'join'
    get 'main_room/join_invite', as: 'join_invite'
    post 'main_room/roomjoininvite'
    post 'main_room/reject_invite', as: 'reject_invite'
    get 'main_room/showroom', as: 'showroom'
    get 'main_room/showhistory', as: 'history'
    post 'res', to: 'main_room#show'
    get 'main_room/rules', as: 'rules'

    post 'rooms/deleteuser', as: 'deleteuser'
    post 'rooms/lottery', as: 'lottery'
    get 'rooms/createroom', as: 'createroom'
    post 'rooms/destroy', as: 'destroyroom'
    post 'rooms/quit', as: 'quit'
    post 'rooms/roomjoin'

    get 'search/add', as: 'add'
    get 'search/input', as: 'search'
    post 'result', to: 'search#show'
    post 'search/addroom', as: 'addroom'

    post 'users/destroy', as: 'destroy'

    resources :users, :rooms
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]
  def login; end

  def create
    user = User.find_by_username(params[:username])
    if user&.authenticate(params[:password])
      sign_in user 
      redirect_to main_path
    else
      redirect_to session_login_url, notice: t('.error')
    end
  end

  def logout
    sign_out
    redirect_to main_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 7.days }
    # signed шифрует id пользователя, добавляем срок годности куки, чтобы пользователя не выкидывало во время сессии
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
    # ||= <=> @current_user = User.find if @current_user.nil?
  end
end

app/views/session/login.html.erb
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <div class="mb-md-5 mt-md-4 pb-5">
            <%=form_with url: session_create_url, method: :post, local:true do |f|%>
              <h2 class="fw-bold mb-2 text-uppercase"> <%= t('.log') %> </h2>
              <p class="text-white-50 mb-5"> <%= t('.inp') %> </p id="logres">
                            <%unless flash[:notice].blank?%>
                <h2 style = 'color:red'><%=flash[:notice]%></h2>
            <%end%>
            <br>
              <div class="form-outline form-white mb-4">
                <%=f.text_field :username, require: true, class: "form-control form-control-lg" %>
                <label class="form-label" for="typeEmailX"> <%= t('.username') %> </label>
              </div>

              <div class="form-outline form-white mb-4">
                <%=f.password_field :password, require: true, class:"form-control form-control-lg" %>
                <label class="form-label" for="typePasswordX"> <%= t('.password') %> </label>
              </div>
                <%=f.submit t('.log'), class: "btn btn-outline-light btn-lg px-5", require: true, id:'loguser'%>
            </div>
            <div>
              <p class="mb-1"> <%= t('.que') %> 
              <%=link_to t('.reg'), new_user_path, class: "text-white-50 fw-bold"%>
              </p>
            </div>
            <div>
            <%= link_to t('.to_main'), main_path, class: "text-white-90 fw-bold"%>
            </div>
            <%end%>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>