config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'search/input'
    post 'session/login'
    get 'session/logout'
    post 'session/logout'
    get 'session/login'
    post 'session/create'

    root 'main_room#main', as: 'main'
    get 'main_room/profile', as: 'profile'
    get 'main_room/join', as: 'join'
    get 'main_room/join_invite', as: 'join_invite'
    post 'main_room/roomjoininvite'
    post 'main_room/reject_invite', as: 'reject_invite'
    get 'main_room/showroom', as: 'showroom'
    get 'main_room/showhistory', as: 'history'
    post 'res', to: 'main_room#show'
    get 'main_room/rules', as: 'rules'

    post 'rooms/deleteuser', as: 'deleteuser'
    post 'rooms/lottery', as: 'lottery'
    get 'rooms/createroom', as: 'createroom'
    post 'rooms/destroy', as: 'destroyroom'
    post 'rooms/quit', as: 'quit'
    post 'rooms/roomjoin'

    get 'search/add', as: 'add'
    get 'search/input', as: 'search'
    post 'result', to: 'search#show'
    post 'search/addroom', as: 'addroom'

    post 'users/destroy', as: 'destroy'

    resources :users, :rooms
  end
end

app/controllers/main_room_controller.rb
class MainRoomController < ApplicationController
  skip_before_action :require_login, only: :main
  before_action :check, only: :roomjoin
  before_action :check_id, only: :showroom

  def main; end

  def profile; end

  def show
    @res = History.where('receiver_id = ?', current_user.id).all
  end

  def createroom
    redirect_to main_path, notice: t('.n') unless signed_in?
    @room = Room.new
  end

  def check
    redirect_to main_path, notice: t('.n') unless signed_in?
  end

  def join; end

  def showroom; end

  def roomjoininvite
    @rm = Room.where('id = ?', params[:id]).take
    if RoomUser.find_by(room_id: @rm.id).gift_user_id
      redirect_to main_room_join_url, notice: t('.lottery')
      return
    end
    if @rm.count_of_users.to_i == RoomUser.where('room_id = ?', @rm.id).all.length
      redirect_to main_room_join_url, notice: t('.full')
      return
    end
    Invite.where('room_id = ? AND user_id = ?', @rm.id, current_user.id).take.destroy
    @newroom = RoomUser.create
    @newroom.update(room_id: @rm.id, user_id: current_user.id, role: 'player', wish: params[:wish],
                    real_username: params[:real_username])
    redirect_to showroom_url(id: @rm.id), notice: t('.success')
  end

  def reject_invite
    Invite.where('room_id = ? AND user_id = ?', Room.where('id = ?', params[:id]).take.id, current_user.id).take.destroy
    redirect_to profile_url(id: Room.where('id = ?', params[:id]).take.id), notice: t('.reject')
  end

  def accept_invite; end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def check_id
    redirect_to main_path, notice: 'Не лезь куда не нужно!' unless RoomUser.find_by(room_id: params[:id],
                                                                                    user_id: current_user.id)
  end
end

app/helpers/main_room_helper.rb
module MainRoomHelper
end

app/views/main_room/_res.html.erb
<div id="result" class="table">
    <table class="table table-striped fs-3 my-3 t">
    <thead>
    <tr>
    <th scope="col"> <%= t('.who') %> </th>
    <th scope="col"> <%= t('.uwish') %> </th>
    <th scope="col"> <%= t('.roomname') %> </th>
    </tr>
    </thead>
    <% @res.each do |x| %>
        <tr>
        <td> <%= x.giver_name %> </td>
        <td class="col-5"> <%= x.receiver_wish %> </td>
        <td class="col-5"> <%= x.room_name %> </td>
        </tr>
    <% end %>
    </table>
</div>

app/views/main_room/join.html.erb
<section class="vh-100" style="background-color: #eee;" >
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1" >
                  <div style="color: red">
                    <ul>
                      <% if @newroom %>
                        <% if @newroom.errors.any? %>
                          <% @newroom.errors.each do |error| %>
                            <li><%= error.message %></li>
                          <%end%>
                         <%end%> 
                      <% end %>
                    </ul>
                  </div>
              <%unless flash[:notice].blank?%>
                <h2 style = 'color:red'><%=flash[:notice]%></h2>
              <%end%>
              <%= form_with url: rooms_roomjoin_url, method: :post,  local:true do |form| %>
                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4"> <%= t('.title') %> </p>
                <form class="mx-1 mx-md-4">

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label t('.room_name'), style: "display: block", class: "form-label"  %>
                         <%= form.text_field :room_name, class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                    <%= form.label t('.password'), style: "display: block", class: "form-label"  %>
                    <%= form.text_field :password , class: "form-control"%>
                    </div>
                  </div>


                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label t('.real_username'), style: "display: block", class: "form-label" %>
                        <%= form.text_field :real_username,  class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label t('.wish'), style: "display: block", class: "form-label" %>
                        <%= form.text_field :wish,  class: "form-control"%>
                    </div>
                  </div>

                  <div class="form-check d-flex justify-content-center mb-5">
                    <label class="form-check-label" for="form2Example3">
                      <%= t('.know') %>  <%= link_to t('.click'), :rules %> 
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <%= form.submit t('.join'), class: "btn btn-primary btn-lg align-items-center", id:"btn_join" %>  
                  </div>
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <%= link_to t('.to_main'), main_path %>
                </div>
                </form>

              </div>
          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://i.artfile.ru/5616x3744_1540035_[www.ArtFile.ru].jpg"
                      class="img-fluid" alt="Sample image"> 

              </div>  


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/main_room/join_invite.html.erb
<section class="vh-100" style="background-color: #eee;" >
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1" >
              <%unless flash[:notice].blank?%>
                <h2 style = 'color:red'><%=flash[:notice]%></h2>
              <%end%>
              <%= form_with url: main_room_roomjoininvite_url(:id => params[:id]), method: :post, local:true do |form| %>
                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4"> <%= t('.remain') %> </p>
                <form class="mx-1 mx-md-4">

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label t('.real'), style: "display: block", class: "form-label" %>
                        <%= form.text_field :real_username,  class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label t('.wish'), style: "display: block", class: "form-label" %>
                        <%= form.text_field :wish,  class: "form-control"%>
                    </div>
                  </div>

                  <div class="form-check d-flex justify-content-center mb-5">
                    <label class="form-check-label" for="form2Example3">
                      <%= t('.rule') %> <a href="#!"> <%= t('.click') %> </a>
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <%= form.submit t('.join'), class: "btn btn-primary btn-lg align-items-center", id:"btn_accept_invite_after_info"%>  
                  </div>
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <%= link_to t('.back'), main_path %>
                </div>
                </form>

              </div>
          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://i.artfile.ru/5616x3744_1540035_[www.ArtFile.ru].jpg"
                      class="img-fluid" alt="Sample image"> 

              </div>  


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/main_room/main.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<div class = "container">

<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
<a href="" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
<svg class="bi me-2" width="40" height="32">
<use xlink:href="#bootstrap"></use>
</svg>
  <span class="fs-1"><%= t('.title')%>
    <div class="fs-1 me-5">
    <%= link_to 'Русский', main_path(locale: :ru) %> |
    <%= link_to 'English', main_path(locale: :en) %> 
  </div>
  </span>

</a>

<ul class="nav nav-pills">
<% if signed_in?%>
<a>
<%=button_to  t('.quit'), session_logout_path, class: "btn btn-outline-primary me-3 fs-2", id: "btn_quit"%>
<%= form_with url: :profile, method: :get do |form| %>
  <%= form.submit t('.view'), id: 'submit-btn', class: "btn btn-primary fs-2", id: "btn_show_profile" %>
  </a>
<% end %>
<%else%>
<%=button_to t('.reg'), new_user_path, method: :get, class: "btn btn-outline-primary me-3 fs-2", id: 'reg'%>
<%=button_to t('.log'), session_login_path, method: :get, class: "btn btn-primary fs-2", id: 'login'%>
<%end%>
</ul>
</header>
</div>

<div class="col-5 mx-auto text-center fs-1 text-light bgo justify-content-center">
<%= t('.new_year') %>
<%= ( Date.new(2022, 12, 31)- Date.today).to_i %>
<%= t('.before') %>
<br>
<%= t('.fast') %>
</div>

<%unless flash[:notice].blank?%>
  <h2 style = 'color:red' id = "notice_main"><%=flash[:notice]%></h2>
<%end%>
<div class="d-grid gap-3 col-3 mx-auto text-center fs-1 container justify-content-center">
<%= form_with url: createroom_url(locale: params[:locale]),params:{locale: params[:locale]} , method: :get do |form| %>
  <%= form.submit t('.create'), id: '1submit-btn', class:"btn btn-primary main_to_btn fs-1" %>
  <br>
<% end %>
<%= form_with url: join_url(locale: params[:locale]), method: :get do |form| %>
  <%= form.submit t('.join'), id: '1submit-btn', class: "btn btn-primary main_to_btn fs-1", id:'btn_join_room' %>
  <br>
<% end %>
<%= form_with url: :search, method: :get do |form| %>
  <%= form.submit t('.send'), id: '1submit-btn', class: "btn btn-primary main_to_btn fs-1", id:"btn_send_invite" %>
  <br>
<% end %>
</div>

<div id="animatedImage" style="position:fixed;padding-top:0px;z-index:99;left:1px;">
 <img id="img1" src="https://i.pinimg.com/originals/d9/6d/15/d96d15973176b36891167fc8a9a43d29.gif" alt="animatedImage" class="m" />
</div>
<script>
var distanceBall=1; 
var directionBall=2; 
document.getElementById('animatedImage').style.top = 1;
document.getElementById('animatedImage').style.left = 1;
var timerToggle=null; 

animateBall();
  function animateBall() {
  document.getElementById("animatedImage").style.left=distanceBall + "px";
  distanceBall+=directionBall;
  if (distanceBall>window.screen.width - 350 ) { 
  document.getElementById('animatedImage').style.top = 1;
  document.getElementById('animatedImage').style.left = 1;
  directionBall = -2;
  document.getElementById('img1').className = 'left';
  }
  if (distanceBall<-40) {
  directionBall = 2;
  document.getElementById('img1').className = 'right';
  }
  timerToggle=setTimeout(function() { animateBall(); }, 1);
  }
  </script>

app/views/main_room/profile.html.erb
<%unless flash[:notice].blank?%>
  <h2 style = 'color:red'><%=flash[:notice]%></h2>
<%end%>
<div class="d-flex flex-column me-4 ">
<div class="container mt-2 d-flex justify-content p-5 text-center justify-content-center">
  <div class="card p-5">
      <div class="d-flex align-items-center">
          <div class="image">
      <img src="https://avatars.mds.yandex.net/i?id=75655f3bfba97552c98e23bd721fc8ef2c5aed1d-8231149-images-thumbs&n=13&exp=1" class="rounded" width="200" >
      </div>
      <div class="ml-3 w-100 px-5 ">
        <h1 class="mb-1"><%= (us = current_user ).username %> </h1>
        <h2><%= us.user_mail %></h2>
        <div class="p-4 mt-1 d-flex justify-content-between rounded text-white stats">
          <div class="d-flex flex-column me-4">
            <h2 class="articles"><%= t('.roomsc')%></h2>
            <h2 class="number1"><%= RoomUser.where('user_id = ?', current_user.id).all.length%></h2>
          </div>
          <div class="d-flex flex-column">
              <h2 class="rating"><%= t('.roomsa')%></h2>
              <h2 class="number3"><%=RoomUser.where("user_id = ? AND role = ?", us.id, 'admin').all.length%></h2>
          </div>
          </div>
          <div class="button mt-3 d-flex flex-row align-items-center g-1 me-2 justify-content-center">
            <%= button_to t('.change'), edit_user_path(id: us, locale: params[:locale]), method: :get, class: "btn btn-sm btn-outline-primary w-150 fs-3 me-3" %>
            <%= button_to t('.deletep'), destroy_url(:id => us, locale: params[:locale]),method: :post, params:{locale: params[:locale]} , class: "btn btn-sm btn-primary w-100 ml-2 fs-3 " %>
          </div>
          <div class="button mt-3 d-flex flex-row g-1 me-1 justify-content-center">
            <%= button_to t('.history'), :history, method: :get, class: "btn btn-sm btn-outline-primary fs-3", style: "width:330px;" %>
          </div>
          <div>
            <h1 class="align-items-center my-2">
              <%= link_to t('.to_main'), main_path, id:"link_back_from_profile"%>
            </h1>
          </div>
      </div>
    </div>
  </div>
</div>

<% if !(t = RoomUser.where("user_id = ?", us.id).all).empty? %>
<div class="p-4 mt-1 d-flex justify-content-between rounded col-md-3 me-4 ">
<%t.each do |x| %>
<%@room = Room.where("id = ?", x.room_id).take%>
<div class="container mt-2 d-flex justify-content p-1 text-center justify-content-center me-2">
  <div class="card p-4 justify-content-center">
      <div class="ml-5 w-100 px-5 ">
          <h1 class="mb-1"> <%= link_to @room.room_name, showroom_url(:id => @room.id), id:"link_to_show_room" %> </h1>
          <%if x.role == 'admin'%>
            <h4 class="mb-1 p-2"> <%= t('.admin')%> </h4>
          <%else%>
            <h4 class="mb-1 p-2"> <%=t('.player') %> </h4>
          <%end%>
          <div class="p-5 mt-2 d-flex justify-content-center rounded text-white stats">
            <div class="d-flex flex-column justify-content-center px-4">
                <h2><%= t('.count')%></h2>
                <% if (l = History.find_by(room_name: @room.room_name)) %>
                <h2> <%= l.all.length %> </h2>
                <%else%>
                <h2><%= RoomUser.where('room_id = ?', @room.id).all.length%> /
                <%= @room.count_of_users%></h2>
                <%end%>
            </div>
          </div>

          <%if x.gift_user_id%>
            <div class="mt-1 fs-4 text-danger">
            <%=t('.lottery')%>
            </div>
          <%end%>
            <%if x.role == 'admin'%>
            <div class="button mt-3 justify-content-center">
              <% unless x.gift_user_id %>
              <%= button_to t('.deleter'), destroyroom_url(:id => @room),method: :post , params:{locale: params[:locale]}, class: "btn btn-sm btn-outline-primary w-150 fs-4" %>
              <% else %>
                <%= button_to t('.quit'), quit_url(:id => @room.id), class: "btn btn-sm btn-outline-primary w-150 fs-4" , params: { id: @room.id }, method: :post%>
              <% end %>
              </div>
            <%else%>
              <div class="button mt-3 justify-content-center">
              <%= button_to t('.quit'), :quit, class: "btn btn-sm btn-outline-primary w-150 fs-4" , params: { id: @room.id }, method: :post%>
              </div>
            <%end%>
      </div>
   </div>
 </div>
<%end %>
<%end%>
</div>


<% if !(t = Invite.where("user_id = ?", us.id).all).empty? %>
<div class="p-4 mt-1 d-flex justify-content-between rounded col-md-4">
<%t.each do |x| %>
  <div class="container mt-1 d-flex justify-content p-1 text-center">
      <div class="card p-4">
        <div class="ml-3 w-100 px-5 ">
          <h4> <%=t('.invite')%> </h4>
          <h1>
          <%= Room.find_by(id: x.room_id).room_name%>
          </h1>
          <h4> <%=t('.from')%> <%=User.find_by(id: x.inviter_id).username%> </h4>
          <div class="button mt-3 d-flex flex-row g-2 justify-content-center">
          <%= button_to t('.accept'), :join_invite ,params: {id: x.room_id} ,method: :get ,class: "btn btn-sm btn-outline-primary fs-3 me-2", id:"btn_accept_invite" %>
          <%= button_to t('.reject'), :reject_invite, params: {id: x.room_id}, method: :post, class: "btn btn-sm btn-primary ml-2 fs-3 " %>
        </div>
      </div>
    </div>
  </div>
<%end%>
<%end%>
</div>

</div>

app/views/main_room/rules.html.erb
<div class=" mt-5  justify-content justify-content-center bgo mx-5">
  <div class="p-5">
  <div class="ml-2 px-1 fs-1">
    <div class="text-center"> <strong>  <%= t('.rule') %> </strong> </div>
    <div class="lh-base">
    <strong> <%= t('.st') %> </strong> <%= t('.p1') %>
    </div>
    <div class="lh-base">
    <%= t('.p2') %>
    </div>
    <div class="lh-base">
    <%= t('.p3') %>
    </div>
    <%= link_to t('.back'), :back, class:"link-light text-center" %>
</div>
</div>
</div>


<div id="animatedImage" style="position:fixed;padding-top:0px;z-index:99;left:1px;">
 <img id="img1" src="https://i.pinimg.com/originals/d9/6d/15/d96d15973176b36891167fc8a9a43d29.gif" alt="animatedImage" class="m" />
</div>
<script>
var distanceBall=1; 
var directionBall=2; 
document.getElementById('animatedImage').style.top = 1;
document.getElementById('animatedImage').style.left = 1;
var timerToggle=null; 

animateBall();
  function animateBall() {
  document.getElementById("animatedImage").style.left=distanceBall + "px";
  distanceBall+=directionBall;
  if (distanceBall>window.screen.width - 350 ) { 
  document.getElementById('animatedImage').style.top = 1;
  document.getElementById('animatedImage').style.left = 1;
  directionBall = -2;
  document.getElementById('img1').className = 'left';
  }
  if (distanceBall<-40) {
  directionBall = 2;
  document.getElementById('img1').className = 'right';
  }
  timerToggle=setTimeout(function() { animateBall(); }, 1);
  }
  </script>

app/views/main_room/show.turbo_stream.erb
<%= turbo_stream.replace 'result', partial: 'res' %>

app/views/main_room/showhistory.html.erb
<% unless (t=History.where('receiver_id = ?', current_user.id).all).empty? || (m=History.where('giver_id = ?', current_user.id).all).empty?%>
    <div class="col-5 mx-auto text-center fs-1 mt-5 ">
    <div class="fs-1 text-white bgo"> <%= t('.title') %> </div>
    <table class="table table-striped fs-2 my-3">
    <thead>
    <tr>
    <th scope="col"> <%= t('.to_whom') %> </th>
    <th scope="col"> <%= t('.wish') %> </th>
    <th scope="col"> <%= t('.roomname') %> </th>
    </tr>
    </thead>
    <% m.each do |x| %>
        <tr>
        <td> <%= x.receiver_name %> </td>
        <td class="col-5"> <%= x.receiver_wish %> </td>
        <td class="col-5"> <%= x.room_name %> </td>
        </tr>
    <% end %>
    </table>

    <div class="fs-1 text-white bgo"> <%= t('.spoiler') %> </div>
    <div class="bgo">
    <%= form_with url: res_path(id: t) do |form| %>
        <%= form.submit t('.btn'), class:"fs-3 btn btn-outline-dark my-3", style:"width:200px" %>
    <%end%>
    </div>
    <div id="result" class="table"> </div>
    <div class="bgo">
    <%= link_to t('.back'), profile_path, class: "link-dark" %>
    </div>
<% else %>
    <div class="col-5 mx-auto text-center fs-1 bgo ">
        <%= t('.pres') %>
        <br>
        <%= link_to t('.back'), profile_path, class: "link-dark" %>
    </div>
<% end %>


</div>

app/views/main_room/showroom.html.erb
<p style="color: green"><%= notice %></p>

<% @room = Room.find(params[:id]) %>

<% unless t = RoomUser.where('room_id = ? AND user_id = ?', @room.id, current_user.id).take.gift_user_id %>
    <%roomuser = RoomUser.where('room_id = ?', @room.id).all%>
  <div class="container mt-1 d-inline-flex justify-content text-center justify-content-center">
    <div class="card p-5">
      <div class="ml-2 w-200 px-2 fs-1">
        <%= t('.info')%>
      </div>
      <div class="image">
        <img src="https://free-png.ru/wp-content/uploads/2021/10/free-png.ru-405.png" class="rounded" width="150" >
      </div>
      <div class="ml-2 w-100 px-2 ">
        <h3> <%=t('.players')%> </h3>
        <div class="mb-3 mt-3 row">
          <% roomuser.each do |el|%>
            <h4 class="mb-2 mt-1">
            <%=el.real_username%> 
            <%if el.role!='admin' && current_user.id == RoomUser.where('room_id = ? AND role = ?', @room.id, 'admin').take.user_id.to_i %>
                <%=button_to t('.delete'), deleteuser_url(:id => @room.id, :uid => el.user_id, locale: params[:locale] ), method: :post, class: "btn btn-sm btn-outline-primary fs-5 my-2"%>
            <%end%>
            </h4> 
          <%end%>
        </div>
        <% if RoomUser.find_by(user_id: current_user.id, room_id: @room.id).role == 'admin'%>
        <%if roomuser.size>=3 %>
          <%= button_to t('.lotter'), lottery_url(id: @room.id), class: "btn btn-sm btn-outline-primary w-150 fs-5", id:"btn_lottery"%>
        <%else%>
          <div class="fs-5"> <%= t('.less') %> </div>
        <%end%>
        <div class="button mt-3 d-flex flex-row align-items-center g-2 justify-content-center">
        <%= button_to t('.edit'), edit_room_url(:id => @room, locale: params[:locale]), method: :get, class: "btn btn-sm btn-outline-primary w-150 fs-5 me-2"%> 
        <%end%>
        <%= button_to t('.back'), :profile, method: :get, class: "btn btn-sm btn-outline-primary w-150 fs-5", id: "btn_back_from_room" %>
        </div>
      </div>
    </div>
  </div>
<%else%>
<div class="container mt-1 d-inline-flex justify-content p-5 text-center justify-content-center">
  <div class="card p-5">
  <div class="d-flex align-items-center  ">
          <div class="image">
      <img src="https://free-png.ru/wp-content/uploads/2021/10/free-png.ru-434.png" class="rounded" width="150" >
    <div class="ml-2 w-100 px-2 ">
      <h3> <%= t('.present') %> </h3>
      <div class="mb-3 mt-3 fs-1">
        <% if (k = RoomUser.find_by(room_id: @room.id, user_id: t)) %>
        <%=  k.real_username %> 
        <%else%>
          <%= History.find_by(room_name: @room.room_name, giver_id: current_user.id).receiver_name%>
        <%end%>
      </div>
      <h3> <%= t('.wish') %> </h3>
         <div class="mb-3 mt-3 fs-1">
        <% if (k = RoomUser.find_by(room_id: @room.id, user_id: t)) %>
        <%=  k.wish%>
        <%else%>
          <%= History.find_by(room_name: @room.room_name, giver_id: current_user.id).receiver_wish%>
        <%end%>
      </div>
      <%= button_to t('.back'), :profile, method: :get %>
    </div>
  </div>
</div>
<%end%>