config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'search/input'
    post 'session/login'
    get 'session/logout'
    post 'session/logout'
    get 'session/login'
    post 'session/create'

    root 'main_room#main', as: 'main'
    get 'main_room/profile', as: 'profile'
    get 'main_room/join', as: 'join'
    get 'main_room/join_invite', as: 'join_invite'
    post 'main_room/roomjoininvite'
    post 'main_room/reject_invite', as: 'reject_invite'
    get 'main_room/showroom', as: 'showroom'
    get 'main_room/showhistory', as: 'history'
    post 'res', to: 'main_room#show'
    get 'main_room/rules', as: 'rules'

    post 'rooms/deleteuser', as: 'deleteuser'
    post 'rooms/lottery', as: 'lottery'
    get 'rooms/createroom', as: 'createroom'
    post 'rooms/destroy', as: 'destroyroom'
    post 'rooms/quit', as: 'quit'
    post 'rooms/roomjoin'

    get 'search/add', as: 'add'
    get 'search/input', as: 'search'
    post 'result', to: 'search#show'
    post 'search/addroom', as: 'addroom'

    post 'users/destroy', as: 'destroy'

    resources :users, :rooms
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :room_name, message: I18n.t('m2')
  validates_presence_of :room_name, message: I18n.t('m1')
  validates_presence_of :password_digest, message: I18n.t('m3')
  validates_confirmation_of :password
  validates :count_of_users, format: { with: /\A[3-9]{1}\z|\A[1-9]+\d+\z/, message: I18n.t('m4') }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy add_to_History quit]
  before_action :check, only: :create
  before_action :add_to_History, only: %i[quit destroy]

  def createroom
    @room = Room.new
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def check
    redirect_to main_path, notice: t('.n') unless signed_in?
  end

  def create
    @room = Room.create(room_params)
    if History.find_by(room_name: @room.room_name)
      redirect_to createroom_url, notice: t('.n1')
      return
    end
    @roomuser = RoomUser.create(roomuser_params)
    @roomuser.room_id = @room.id
    @roomuser.user_id = current_user.id
    @roomuser.role = 'admin'
    if @room.save && @roomuser.save
      redirect_to showroom_url(id: @room.id)
    else
      render 'rooms/createroom', status: :unprocessable_entity
      @room.destroy
      @roomuser.destroy
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to :profile, notice: t('.not') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def deleteuser
    RoomUser.where('user_id = ? AND room_id = ?', params[:uid], params[:id]).take.destroy
    redirect_to showroom_url, notice: t('.success')
  end

  def add_to_History
    if RoomUser.where('room_id = ?', @room.id).take.gift_user_id && !History.where('room_name = ?', @room.room_name)
      RoomUser.where('room_id = ?',
                     @room.id).all.each do |el|
        History.create(giver_name: el.real_username,
                       giver_id: el.user_id,
                       receiver_id: RoomUser.find_by('user_id = ? AND room_id = ?', el.gift_user_id,
                                                     el.room_id).user_id,
                       receiver_name: RoomUser.find_by('user_id = ? AND room_id = ?', el.gift_user_id,
                                                       el.room_id).real_username,
                       receiver_wish: RoomUser.find_by(user_id: el.gift_user_id, room_id: el.room_id).wish,
                       room_name: Room.find_by(id: el.room_id).room_name)
      end
    end
  end

  def destroy
    RoomUser.where('room_id = ?', @room.id).all.each(&:destroy)
    @room.destroy
    redirect_to profile_url, notice: t('.success')
  end

  def quit
    RoomUser.where('room_id = ? AND user_id = ?', params[:id], current_user.id).take.destroy
    Room.find_by(id: params[:id]).destroy unless RoomUser.where('room_id = ?', params[:id]).take
    redirect_to profile_url, notice: t('.success')
  end

  def lottery
    a = []
    RoomUser.where('room_id = ?', params[:id]).all.each { |x| a.push(x.user_id) }
    a.shuffle!.push(a[0]).each_with_index do |el, index|
      unless index == a.length - 1
        RoomUser.find_by(user_id: el,
                         room_id: params[:id]).update(gift_user_id: a[index + 1])
      end
    end
    redirect_to showroom_url(id: params[:id]), notice: t('.success')
  end

  def roomjoin
    @rm = Room.where('room_name = ?', params[:room_name]).take
    unless @rm
      redirect_to :join, notice: t('.not_room')
      return
    end
    if RoomUser.find_by(room_id: @rm.id).try(:gift_user_id)
      redirect_to :join, notice: t('.lottery')
      return
    end
    unless RoomUser.find_by(room_id: @rm.id)
      redirect_to :join, notice: t('.lottery')
      return
    end
    if @rm.count_of_users.to_i == RoomUser.where('room_id = ?', @rm.id).all.length
      redirect_to :join, notice: t('.full')
      return
    end
    if @rm&.authenticate(params[:password])
      if RoomUser.where('room_id = ? AND user_id = ?', @rm.id, current_user.id).take
        redirect_to :join, notice: t('.user')
        return
      end
      if (t = Invite.where('room_id = ? AND user_id = ?', @rm.id, current_user.id).take)
        t.destroy
      end
      @newroom = RoomUser.create
      if @newroom.update(room_id: @rm.id, user_id: current_user.id, role: 'player', wish: params[:wish],
                         real_username: params[:real_username])
        redirect_to showroom_url(id: @rm.id), notice: t('.success')
      else
        render 'main_room/join', status: :unprocessable_entity
      end
    else
      redirect_to join_url, notice: t('.password')
    end
  end

  private

  def room_params
    params.require(:room).permit(:room_name, :password, :password_confirmation,
                                 :count_of_users)
  end

  def roomuser_params
    params.require(:room).permit(:wish, :real_username)
  end
end

app/views/rooms/_create.html.erb
<section class="vh-100" style="background-color: #eee;" >
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1" >
              <%= form_with(model: room, locale: params[:locale]) do |form| %>
                <% if room.errors.any? %>
                  <div style="color: red">
                    <ul>
                      <% room.errors.each do |error| %>
                        <li><%= error.message %></li>
                      <% end %>
                      <% if @roomuser %>
                        <% if @roomuser.errors.any? %>
                          <% @roomuser.errors.each do |error| %>
                            <li><%= error.message %></li>
                          <%end%>
                         <%end%> 
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <%unless flash[:notice].blank?%>
  <h2 style = 'color:red'><%=flash[:notice]%></h2>
<%end%>
                
                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4"><%=t('.title')%></p>
                <form class="mx-1 mx-md-4">
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :room_name, style: "display: block", class: "form-label"  %>
                         <%= form.text_field :room_name, class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                    <%= form.label :password , style: "display: block", class: "form-label"  %>
                    <%= form.password_field :password , class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :password_confirmation, style: "display: block", class: "form-label" %>
                       <%= form.password_field :password_confirmation, class: "form-control" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :count_of_users, style: "display: block", class: "form-label" %>
                        <%= form.text_field :count_of_users,  class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :real_username, style: "display: block", class: "form-label" %>
                        <%= form.text_field :real_username,  class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :wish, style: "display: block", class: "form-label" %>
                        <%= form.text_field :wish,  class: "form-control"%>
                    </div>
                  </div>

                  <div class="form-check d-flex justify-content-center mb-5">
                    <label class="form-check-label" for="form2Example3">
                      <%= t('.know') %>  <%= link_to t('.click'), :rules %>
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <%= form.submit t('.create'), class: "btn btn-primary btn-lg align-items-center", id: "btn_createroom"%>  
                  </div>
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <%= link_to t('.to_main'), main_path %>
                </div>
                </form>

              </div>
          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://i.artfile.ru/3549x3100_1283670_[www.ArtFile.ru].jpg"
                      class="img-fluid" alt="Sample image"> 

              </div>  


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/rooms/_editroom.html.erb
<section class="vh-100" style="background-color: #eee;" >
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1" >
              <%= form_with(model: room) do |form| %>
                <% if room.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(room.errors.count, "error") %> </h2>

                    <ul>
                      <% room.errors.each do |error| %>
                        <li><%= error.message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Хочешь изменить комнату?</p>
                <form class="mx-1 mx-md-4">
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :room_name, style: "display: block", class: "form-label"  %>
                         <%= form.text_field :room_name, class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                    <%= form.label :password_digest, style: "display: block", class: "form-label"  %>
                    <%= form.text_field :password , class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :lbl, value: 'Подтвердите пароль', style: "display: block", class: "form-label" %>
                       <%= form.password_field :password_confirmation, class: "form-control" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :count_of_users, style: "display: block", class: "form-label" %>
                        <%= form.text_field :count_of_users,  class: "form-control"%>
                    </div>
                  </div>


                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <%= form.submit "внести изменения", class: "btn btn-primary btn-lg align-items-center"%>  
                  </div>
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <%= link_to "Вернуться в комнату", showroom_path(:id => @room.id) %>
                </div>
                </form>

              </div>
          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://i.artfile.ru/3549x3100_1283670_[www.ArtFile.ru].jpg"
                      class="img-fluid" alt="Sample image"> 

              </div>  
<% end %>


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/rooms/_join.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> </h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :room_number, style: "display: block" %>
    <%= form.text_field :room_number %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

    <div>
    <%= form.label :user_wish, style: "display: block" %>
    <%= form.text_field :user_wish %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<section class="vh-100" style="background-color: #eee;" >
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1" >
              <%= form_with(model: room) do |form| %>
                <% if room.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(room.errors.count, "error") %> </h2>

                    <ul>
                      <% room.errors.each do |error| %>
                        <li><%= error.message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                
                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4"> <%= t('.que') %> </p>
                <form class="mx-1 mx-md-4">
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :room_name, style: "display: block", class: "form-label"  %>
                         <%= form.text_field :room_name, class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                    <%= form.label :password, style: "display: block", class: "form-label"  %>
                    <%= form.text_field :password , class: "form-control"%>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :password_confirmation, style: "display: block", class: "form-label" %>
                       <%= form.password_field :password_confirmation, class: "form-control" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= form.label :count_of_users, style: "display: block", class: "form-label" %>
                        <%= form.text_field :count_of_users,  class: "form-control"%>
                    </div>
                  </div>


                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <%= form.submit t('.edit'), class: "btn btn-primary btn-lg align-items-center"%>  
                  </div>
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <%= link_to t('.back'), showroom_path(:id => @room.id) %>
                </div>
                </form>

              </div>
          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://i.artfile.ru/3549x3100_1283670_[www.ArtFile.ru].jpg"
                      class="img-fluid" alt="Sample image"> 

              </div>  
<% end %>


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/rooms/createroom.html.erb
<%= render "create", room: @room, roomuser: @roomuser %>

app/views/rooms/edit.html.erb
<%= render "room", room: @room, params:{locale: params[:locale]} %>